version: '3.1'
services:
  prserver:
    command: ["chmod", "+x", "start.sh"]
    container_name: prserver
    entrypoint: ./start.sh
    networks: 
      - default 
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - "16567:16567"
      - "29900:29900"
      - "55123-55125:55123-55125"
    volumes:
      - /tmp/prserver:/opt/pr
      
networks:
  default:
    driver: host